main: de.kaleidox.jumpcube.JumpCube
name: ${rootProject.name}
version: ${version}
author: Kaleidox
description: Continuation of the DeathCube plugin
api-version: ${apiLevel}
softdepend:
  - Spiroid
commands:
  jumpcube:
    description: JumpCube command
    aliases:
      - jc
